### ISSUE TITLE
Please update dependency on google-api-python-client 

### ISSUE THREAD

**Issue by munkien** [GoogleCloudPlatform/cloud-profiler-python#87] opened 2021-04-20 21:35 UTC
Hi

I have a problem where I use google-api-python-client V2 which this library does not yet support :-)
Please update it so it can be used with V2 of google-api-python client

`
Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because google-cloud-profiler (3.0.3) depends on google-api-python-client (<1.12.0 || >1.12.0,<2)
   and no versions of google-cloud-profiler match >3.0.3,<4.0.0, google-cloud-profiler (>=3.0.3,<4.0.0) requires google-api-python-client (<1.12.0 || >1.12.0,<2).
  So, because project-name depends on both google-api-python-client (^2.2.0) and google-cloud-profiler (^3.0.3), version solving failed.
`

**Comment by wyk9787** [comment] 2021-04-21 23:48
Thanks for reporting the issue! We are aware of this dependency version restriction. The reason for not using client library V2 was an incompatibility issue: https://github.com/googleapis/google-api-python-client/issues/1225. Now that the issue is resolved by https://github.com/googleapis/google-api-python-client/pull/1261, we should be able to get a new version of the Cloud Profiler out to use client library V2.1.0+. 

I will update here when a new version is released. Ideally before end of the week, if not, definitely next week. Thanks for your patience!

**Comment by munkien** [comment] 2021-04-22 14:09
Hey Garrett!
Thanks for the fast reply.
Yes, thats perfect! 

Have a great week :-)

**Comment by wyk9787** [comment] 2021-04-28 14:48
V3.0.4 was released: https://pypi.org/project/google-cloud-profiler/3.0.4/.

You should now be able to use google-api-python-client V2.1.0+.

**Closed** 2021-04-28 14:49 UTC
